# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GlobalNote' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'CocoaLumberjack', '~> 3.5.2'
    pod 'fishhook', '~> 0.2'
  # Pods for GlobalNote

  target 'GlobalNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GlobalNoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
